const mongoose = require ('mongoose');
const dadosSchema = new mongoose.Schema({
    dadosTabela: [[String]],
    dadosTabela2: [[String]],
    dadosTabela3: [[String]],
    dadosTabela4: [[String]],
    dadosTabela5: [[String]],
    dadosTabela6: [[String]],
    dadosTabela7: [[String]],
    dadosTabela8: [[String]],
    dadosTabela9: [[String]],
    dadosTabela10: [[String]],
    dadosTabela11: [[String]],
    anoAtual: String,
    anoAtual2: String,
    anoAtual3: String,
    anoAtual4: String,
    anoAtual5: String,
    anoAtual6: String,
    anoAtual7: String,
    anoAtual8: String,
    anoAtual9: String,
    anoAtual10: String,
    anoAtual11: String,
    clubeSelecionado1: "Ajax",
    clubeSelecionado2: "Al Ittihad",
    clubeSelecionado3: "Barnsley",
    clubeSelecionado4: "Boca Juniors",
    clubeSelecionado5: "Gent",
    clubeSelecionado6: "Hannover 96",
    clubeSelecionado7: "Leeds United",
    clubeSelecionado8: "Liverpool",
    clubeSelecionado9: "Newell's Old Boys",
    clubeSelecionado10: "Olympique Lyonnais",
    clubeSelecionado11: "Zürich",
})
const Dados = mongoose.model('Dados', dadosSchema);
module.exports = Dados;